language: node_js
node_js:
  - "node"

sudo: false

branches:
  only:
  - master
  - develop
  - /^[0-9]+\.[0-9]+\.[0-9]+$/

cache:
  directories:
  - $HOME/.composer/cache

notifications:
  email:
  - npmjs@evoweb.de

install:
  - >
    npm install jshint@2.6.0 --save-dev;
    git checkout package.json;

script:
- >
  echo "No tests implemented";

jobs:
  include:
  - stage: test
    env: TASK="JavaScript Lint"
    before_install: skip
    before_script: skip
    script:
    - echo "Running javascript hint";
      ./node_modules/jshint/bin/jshint lib/

  - stage: publish in npmjs.org
    if: tag IS present
    php: 7.0
    before_install: skip
    install: skip
    before_script: skip
    script:
    - |
      if [ -n "$NPM_TOKEN" ]; then
        echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
        npm publish
      fi;
